export const data = {
  fr: {
    personalInfo: {
      name: "Space Informatik",
      ceo: "Djidepo Kokou Norbert NKRO",
      title: "Solutions Digitales Innovantes | Big Data & IA",
      bio: "Space Informatik est bien plus qu'une entreprise de développement ; c'est un partenaire stratégique pour l'innovation. Fondée avec la vision de propulser les entreprises africaines et internationales vers le futur, nous concevons des écosystèmes numériques complets. De l'infrastructure Cloud robuste aux interfaces utilisateur captivantes, en passant par l'analyse prédictive via l'IA, nous transformons des défis complexes en opportunités de croissance durable.",
      email: "nkro006@gmail.com",
      phone: "00(228)70839500 / 00(228)70152456",
      location: "Avedji, 55788, Lomé, Togo",
      linkedin: "linkedin.com/in/norbert-nkro-143576187",
      github: "github.com/nkrokokou",
    },
    skills: [
      { name: "Vibe Coding (Cursor/AI)", category: "Innovation" },
      { name: "Python (Flask, Django)", category: "Backend" },
      { name: "Flutter & Dart", category: "Mobile" },
      { name: "PHP (Laravel)", category: "Backend" },
      { name: "HTML/CSS/JS", category: "Frontend" },
      { name: "C/C++", category: "Systèmes" },
      { name: "SQL & NoSQL", category: "Base de données" },
      { name: "Big Data & IA", category: "Data" },
      { name: "Virtualisation", category: "DevOps" },
      { name: "Next.js & React", category: "Frontend" },
      { name: "FastAPI", category: "Backend" },
    ],
    experience: [
      {
        title: "Partenariat Technologique",
        company: "AMAP Togo",
        location: "Lomé, Togo",
        period: "En cours",
        description: [
          "Développement de solutions digitales pour l'agriculture durable et les circuits courts.",
          "Mise en place d'une plateforme de mise en relation entre producteurs locaux et consommateurs.",
          "Conception d'outils de gestion pour les associations de maintien de l'agriculture paysanne.",
          "Support technique et accompagnement dans la transformation numérique du secteur agricole.",
        ],
      },
      {
        title: "Partenariat Technologique",
        company: "Kekeli Efficient Power",
        location: "Lomé, Togo",
        period: "En cours",
        description: [
          "Développement et maintenance du système d'information de l'entreprise.",
          "Conception de solutions digitales pour optimiser les processus internes.",
          "Support technique et formation des équipes.",
        ],
      },
      {
        title: "Projets de Transformation Digitale",
        company: "Kheir Media",
        location: "Lomé, Togo",
        period: "11/2022 – 06/2023",
        description: [
          "Optimisation et refonte d'applications web pour améliorer la performance.",
          "Collaboration avec des équipes multidisciplinaires sur des projets innovants.",
          "Analyse des besoins clients et conception de solutions sur mesure.",
          "Développement full-stack d'applications web et mobiles.",
        ],
      },
    ],
    projects: [
      {
        title: "Shalo Snap Photo",
        description: "Portfolio professionnel pour un photographe contemporain, mettant en valeur des portraits, mariages et événements spéciaux. Design élégant et galerie immersive.",
        link: "http://shalosnapphoto.com",
        tags: ["Photographie", "Portfolio", "Design"],
        image: "/images/shalo.png",
      },
      {
        title: "DressingFlow",
        description: "Plateforme e-commerce de mode offrant une expérience d'achat fluide. Intégration de paiements et gestion de catalogue.",
        link: "http://dressingflow.com",
        tags: ["E-commerce", "Mode", "Web"],
        image: "/images/dressingflow.png",
      },
      {
        title: "Cantine Kekeli",
        description: "Application de gestion de repas 'Les Délices de Victoire' pour entreprises. Optimisation des commandes, espace employés et administration complète.",
        link: "https://cantine-kekeli-efficient-power-eranove-alp2gbw1nvcgrpkq.builder-preview.com",
        tags: ["Web App", "Gestion", "SaaS"],
        image: "/images/cantine.png",
      },
      {
        title: "Fermagroecologie",
        description: "Plateforme dédiée à l'agroécologie, connectant les agriculteurs aux pratiques durables et offrant des ressources éducatives pour une agriculture respectueuse de l'environnement.",
        link: "http://fermagroecologie.org",
        tags: ["Ecologie", "Agriculture", "Education"],
        image: "/images/fermagro.png",
      },
      {
        title: "FindMe",
        description: "Application de géolocalisation innovante permettant de retrouver des objets ou personnes en temps réel. Interface intuitive et fonctionnalités de tracking sécurisées.",
        link: "https://lavenderblush-capybara-317038.hostingersite.com/",
        tags: ["Géolocalisation", "App", "Utilitaire"],
        image: "/images/findme.png",
      },
      {
        title: "Lomé Services",
        description: "Plateforme de mise en relation entre prestataires de services locaux et clients à Lomé. Catégories variées avec contact direct via WhatsApp.",
        link: "https://lome-service-app.vercel.app/",
        tags: ["Marketplace", "Services", "WhatsApp"],
        image: "/images/lome-services.png",
      },
      {
        title: "Malodoc V2",
        description: "Plateforme de santé moderne connectant patients et médecins vérifiés. Réservation de consultations en ligne, créneaux solidaires, et gestion de pharmacie.",
        link: "https://malodoc-v2.vercel.app/",
        tags: ["Santé", "SaaS", "Web App"],
        image: "/images/malodoc.png",
      },
      {
        title: "Ziris",
        description: "Projet full-stack combinant un backend FastAPI (Python) et un frontend React TypeScript. Architecture moderne avec documentation complète.",
        link: "https://github.com/nkrokokou/ziris",
        tags: ["Full-Stack", "FastAPI", "React", "Open Source"],
        image: "/images/ziris.png",
      },
      {
        title: "Gestion de Conformité",
        description: "Application mobile de gestion de conformité réglementaire et normative. Suivi des normes ISO 14001:2015, RGPD, et gestion des risques.",
        link: "https://lemonchiffon-magpie-493788.hostingersite.com/",
        tags: ["App Mobile", "Conformité", "ISO", "RGPD"],
        image: "/images/compliance-app.png",
      },
      {
        title: "CEFAPE Togo",
        description: "Site web moderne pour le Centre de Formation Agricole et de Production Écologique. Modèle 3D interactif de plant de tomate et informations complètes sur l'agriculture durable.",
        link: "https://cefape-togo.vercel.app/",
        tags: ["Formation", "Agriculture", "3D", "Web"],
        image: "/images/cefape.jpeg",
      },
    ]
  },
  en: {
    personalInfo: {
      name: "Space Informatik",
      ceo: "Djidepo Kokou Norbert NKRO",
      title: "Innovative Digital Solutions | Big Data & AI",
      bio: "Space Informatik is more than a development company; it is a strategic partner for innovation. Founded with the vision of propelling African and international companies into the future, we design complete digital ecosystems. From robust Cloud infrastructure to captivating user interfaces, including predictive analysis via AI, we turn complex challenges into sustainable growth opportunities.",
      email: "nkro006@gmail.com",
      phone: "00(228)70839500 / 00(228)70152456",
      location: "Avedji, 55788, Lomé, Togo",
      linkedin: "linkedin.com/in/norbert-nkro-143576187",
      github: "github.com/nkrokokou",
    },
    skills: [
      { name: "Vibe Coding (Cursor/AI)", category: "Innovation" },
      { name: "Python (Flask, Django)", category: "Backend" },
      { name: "Flutter & Dart", category: "Mobile" },
      { name: "PHP (Laravel)", category: "Backend" },
      { name: "HTML/CSS/JS", category: "Frontend" },
      { name: "C/C++", category: "Systems" },
      { name: "SQL & NoSQL", category: "Database" },
      { name: "Big Data & AI", category: "Data" },
      { name: "Virtualization", category: "DevOps" },
      { name: "Next.js & React", category: "Frontend" },
      { name: "FastAPI", category: "Backend" },
    ],
    experience: [
      {
        title: "Technology Partnership",
        company: "AMAP Togo",
        location: "Lomé, Togo",
        period: "Ongoing",
        description: [
          "Development of global solutions for sustainable agriculture and short supply chains.",
          "Implementation of a platform connecting local producers and consumers.",
          "Design of management tools for peasant farming associations.",
          "Technical support and guidance in the digital transformation of the agricultural sector.",
        ],
      },
      {
        title: "Technology Partnership",
        company: "Kekeli Efficient Power",
        location: "Lomé, Togo",
        period: "Ongoing",
        description: [
          "Development and maintenance of the company's information system.",
          "Design of digital solutions to optimize internal processes.",
          "Technical support and team training.",
        ],
      },
      {
        title: "Digital Transformation Projects",
        company: "Kheir Media",
        location: "Lomé, Togo",
        period: "11/2022 – 06/2023",
        description: [
          "Optimization and redesign of web applications to improve performance.",
          "Collaboration with multidisciplinary teams on innovative projects.",
          "Client needs analysis and custom solution design.",
          "Full-stack development of web and mobile applications.",
        ],
      },
    ],
    projects: [
      {
        title: "Shalo Snap Photo",
        description: "Professional portfolio for a contemporary photographer, showcasing portraits, weddings, and special events. Elegant design and immersive gallery.",
        link: "http://shalosnapphoto.com",
        tags: ["Photography", "Portfolio", "Design"],
        image: "/images/shalo.png",
      },
      {
        title: "DressingFlow",
        description: "Fashion e-commerce platform offering a seamless shopping experience. Payment integration and catalog management.",
        link: "http://dressingflow.com",
        tags: ["E-commerce", "Fashion", "Web"],
        image: "/images/dressingflow.png",
      },
      {
        title: "Cantine Kekeli",
        description: "'Les Délices de Victoire' meal management app for companies. Order optimization, employee area, and complete administration.",
        link: "https://cantine-kekeli-efficient-power-eranove-alp2gbw1nvcgrpkq.builder-preview.com",
        tags: ["Web App", "Management", "SaaS"],
        image: "/images/cantine.png",
      },
      {
        title: "Fermagroecologie",
        description: "Platform dedicated to agroecology, connecting farmers to sustainable practices and offering educational resources for eco-friendly agriculture.",
        link: "http://fermagroecologie.org",
        tags: ["Ecology", "Agriculture", "Education"],
        image: "/images/fermagro.png",
      },
      {
        title: "FindMe",
        description: "Innovative geolocation application to find objects or people in real-time. Intuitive interface and secure tracking features.",
        link: "https://lavenderblush-capybara-317038.hostingersite.com/",
        tags: ["Geolocation", "App", "Utility"],
        image: "/images/findme.png",
      },
      {
        title: "Lomé Services",
        description: "Connecting local service providers and clients in Lomé. Various categories with direct contact via WhatsApp.",
        link: "https://lome-service-app.vercel.app/",
        tags: ["Marketplace", "Services", "WhatsApp"],
        image: "/images/lome-services.png",
      },
      {
        title: "Malodoc V2",
        description: "Modern health platform connecting patients and verified doctors. Online consultation booking, solidarity slots, and pharmacy management.",
        link: "https://malodoc-v2.vercel.app/",
        tags: ["Healthcare", "SaaS", "Web App"],
        image: "/images/malodoc.png",
      },
      {
        title: "Ziris",
        description: "Full-stack project combining FastAPI (Python) backend and React TypeScript frontend. Modern architecture with full documentation.",
        link: "https://github.com/nkrokokou/ziris",
        tags: ["Full-Stack", "FastAPI", "React", "Open Source"],
        image: "/images/ziris.png",
      },
      {
        title: "Compliance Management",
        description: "Regulatory and normative compliance management mobile application. ISO 14001:2015 monitoring, GDPR, and risk management.",
        link: "https://lemonchiffon-magpie-493788.hostingersite.com/",
        tags: ["Mobile App", "Compliance", "ISO", "GDPR"],
        image: "/images/compliance-app.png",
      },
      {
        title: "CEFAPE Togo",
        description: "Modern website for the Centre de Formation Agricole et de Production Écologique. 3D interactive tomato plant model and comprehensive information about sustainable agriculture.",
        link: "https://cefape-togo.vercel.app/",
        tags: ["Education", "Agriculture", "3D", "Web"],
        image: "/images/cefape.png",
      },
    ]
  }
};
