export const data = {
  fr: {
    personalInfo: {
      name: "Space Informatik",
      ceo: "Djidepo Kokou Norbert NKRO",
      title: "Solutions Digitales Innovantes | Big Data & IA",
      bio: "Space Informatik est bien plus qu'une entreprise de développement ; c'est un partenaire stratégique pour l'innovation. Fondée avec la vision de propulser les entreprises africaines et internationales vers le futur, nous concevons des écosystèmes numériques complets. De l'infrastructure Cloud robuste aux interfaces utilisateur captivantes, en passant par l'analyse prédictive via l'IA, nous transformons des défis complexes en opportunités de croissance durable.",
      email: "nkro006@gmail.com",
      phone: "00(228)70839500 / 00(228)70152456",
      location: "Avedji, 55788, Lomé, Togo",
      linkedin: "linkedin.com/in/norbert-nkro-143576187",
      github: "github.com/nkrokokou",
    },
    skills: [
      { name: "Méthodologies Agile & CI/CD", category: "Innovation" },
      { name: "Python (Flask, Django)", category: "Backend" },
      { name: "Flutter & Dart", category: "Mobile" },
      { name: "PHP (Laravel)", category: "Backend" },
      { name: "HTML/CSS/JS", category: "Frontend" },
      { name: "C/C++", category: "Systèmes" },
      { name: "SQL & NoSQL", category: "Base de données" },
      { name: "Big Data & IA", category: "Data" },
      { name: "Virtualisation", category: "DevOps" },
      { name: "Next.js & React", category: "Frontend" },
      { name: "FastAPI", category: "Backend" },
      { name: "Supabase", category: "Base de données" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Three.js / React Three Fiber", category: "Frontend" },
      { name: "Streamlit", category: "Frontend" },
      { name: "Turborepo", category: "DevOps" },
    ],
    experience: [
      {
        title: "Partenariat Technologique",
        company: "AMAP Togo",
        location: "Lomé, Togo",
        period: "En cours",
        description: [
          "Développement de solutions digitales pour l'agriculture durable et les circuits courts.",
          "Mise en place d'une plateforme de mise en relation entre producteurs locaux et consommateurs.",
          "Conception d'outils de gestion pour les associations de maintien de l'agriculture paysanne.",
          "Support technique et accompagnement dans la transformation numérique du secteur agricole.",
        ],
      },
      {
        title: "Partenariat Technologique",
        company: "Kekeli Efficient Power",
        location: "Lomé, Togo",
        period: "En cours",
        description: [
          "Développement et maintenance du système d'information de l'entreprise.",
          "Conception de solutions digitales pour optimiser les processus internes.",
          "Support technique et formation des équipes.",
        ],
      },
      {
        title: "Projets de Transformation Digitale",
        company: "Kheir Media",
        location: "Lomé, Togo",
        period: "11/2022 – 06/2023",
        description: [
          "Optimisation et refonte d'applications web pour améliorer la performance.",
          "Collaboration avec des équipes multidisciplinaires sur des projets innovants.",
          "Analyse des besoins clients et conception de solutions sur mesure.",
          "Développement full-stack d'applications web et mobiles.",
        ],
      },
    ],
    projects: [
      {
        title: "Phone Shop Manager",
        description: "Solution complète de gestion pour boutiques de téléphonie : Point de vente (POS), suivi des réparations (IMEI, pannes), module de microfinance (Tontine) et centre de formation. Une application robuste avec export PDF, rapports financiers et gestion de stock intelligente.",
        link: "https://phoneshop-manager.vercel.app/",
        github: "https://github.com/nkrokokou/phoneshop_manager",
        tags: ["SaaS", "ERP", "Vente", "Réparation", "Finance"],
        image: "icon:Smartphone",
      },
      {
        title: "Shalo Snap Photo",
        description: "Portfolio professionnel pour un photographe contemporain, mettant en valeur des portraits, mariages et événements spéciaux. Design élégant et galerie immersive.",
        tags: ["Photographie", "Portfolio", "Design"],
        image: "/images/shalo.png",
        isCompleted: true,
      },
      {
        title: "DressingFlow",
        description: "Plateforme e-commerce de mode offrant une expérience d'achat fluide. Intégration de paiements et gestion de catalogue.",
        github: "https://github.com/nkrokokou/dressingflow",
        tags: ["E-commerce", "Mode", "Web"],
        image: "/images/dressingflow.png",
      },
      {
        title: "Cantine Kekeli",
        description: "Application de gestion de repas 'Les Délices de Victoire' pour entreprises. Optimisation des commandes, espace employés et administration complète.",
        tags: ["Web App", "Gestion", "SaaS"],
        image: "/images/cantine.png",
        isCompleted: true,
      },
      {
        title: "Fermagroecologie",
        description: "Plateforme dédiée à l'agroécologie, connectant les agriculteurs aux pratiques durables et offrant des ressources éducatives pour une agriculture respectueuse de l'environnement.",
        tags: ["Ecologie", "Agriculture", "Education"],
        image: "/images/fermagro.png",
        isCompleted: true,
      },
      {
        title: "FindMe",
        description: "Application de géolocalisation innovante permettant de retrouver des objets ou personnes en temps réel. Interface intuitive et fonctionnalités de tracking sécurisées.",
        tags: ["Géolocalisation", "App", "Utilitaire"],
        image: "/images/findme.png",
        isCompleted: true,
      },
      {
        title: "Lomé Services",
        description: "Plateforme de mise en relation entre prestataires de services locaux et clients à Lomé. Catégories variées avec contact direct via WhatsApp.",
        github: "https://github.com/nkrokokou/lome-services",
        tags: ["Marketplace", "Services", "WhatsApp"],
        image: "/images/lome-services.png",
      },
      {
        title: "Malodoc V2",
        description: "Plateforme de santé moderne connectant patients et médecins vérifiés. Réservation de consultations en ligne, créneaux solidaires, et gestion de pharmacie.",
        github: "https://github.com/nkrokokou/malodoc-v2",
        tags: ["Santé", "SaaS", "Web App"],
        image: "/images/malodoc.png",
      },
      {
        title: "Ziris",
        description: "Projet full-stack combinant un backend FastAPI (Python) et un frontend React TypeScript. Architecture moderne avec documentation complète.",
        github: "https://github.com/nkrokokou/ziris",
        tags: ["Full-Stack", "FastAPI", "React", "Open Source"],
        image: "/images/ziris.png",
      },
      {
        title: "Gestion de Conformité",
        description: "Application mobile de gestion de conformité réglementaire et normative. Suivi des normes ISO 14001:2015, RGPD, et gestion des risques.",
        tags: ["App Mobile", "Conformité", "ISO", "RGPD"],
        image: "/images/compliance-app.png",
        isCompleted: true,
      },
      {
        title: "CEFAPE Togo",
        description: "Site web moderne pour le Centre de Formation Agricole et de Production Écologique. Modèle 3D interactif de plant de tomate et informations complètes sur l'agriculture durable.",
        link: "https://cefape-togo.vercel.app/",
        github: "https://github.com/nkrokokou/cefape-togo",
        tags: ["Formation", "Agriculture", "3D", "Web"],
        image: "/images/cefape.jpeg",
      },
      {
        title: "AMAP Togo",
        description: "Plateforme e-commerce et de gestion complète pour l'Association pour le Maintien d'une Agriculture Paysanne au Togo. Monorepo intégrant un catalogue bio, la gestion de paniers hebdomadaires, un point de vente (POS) et un back-office d'administration.",
        link: "https://www.fermagroecologie.org/",
        github: "https://github.com/nkrokokou/amap-togo",
        tags: ["Next.js", "Supabase", "Turborepo", "Monorepo", "E-commerce", "SaaS"],
        image: "icon:Leaf",
      },
      {
        title: "EduPerformance",
        description: "Plateforme d'évaluation des performances scolaires. Dashboard interactif avec indicateurs clés (KPIs), graphiques dynamiques (Chart.js), traitement de données avec Pandas et architecture modulaire FastAPI.",
        link: "https://edu-performance.vercel.app",
        github: "https://github.com/nkrokokou/edu_performance",
        tags: ["FastAPI", "Pandas", "Python", "Chart.js", "Bootstrap"],
        image: "icon:GraduationCap",
      },
      {
        title: "Saadé Management",
        description: "Système complet de gestion pour le restaurant/salon Saadé. Interface 3D interactive (Three.js/Framer Motion) intégrant des modules de gestion de stock, d'inventaire, de pertes cuisine, de ressources humaines et de comptabilité.",
        link: "https://proshop-ultra.vercel.app",
        github: "https://github.com/nkrokokou/proshop-ultra",
        tags: ["React", "Three.js", "Framer Motion", "Tailwind CSS", "Dashboard 3D"],
        image: "icon:Utensils",
      },
      {
        title: "Resume Matcher AI",
        description: "Assistant intelligent de screening de CV et de préparation d'entretiens. Analyse le taux de correspondance (NLP) entre un CV (PDF/DOCX) et une offre, identifie les compétences manquantes et génère des questions d'entretien ciblées (OpenRouter API).",
        tags: ["Python", "Streamlit", "LLM / AI", "NLP", "HR Tech"],
        image: "icon:Users",
        isCompleted: true,
      },
      {
        title: "Saadé Good Vibes",
        description: "Pâtisserie poétique, douceurs faites main, concept-store et hot dogs gourmets à Lomé. Un univers chaleureux alliant gourmandise et partage.",
        link: "https://saade-good-vibes.lovable.app/",
        tags: ["Pâtisserie", "Concept-store", "Restauration", "Lomé"],
        image: "icon:Store",
      },
      {
        title: "InterviewMate",
        description: "Entraînez-vous pour vos entretiens d'embauche avec un coach IA. Collez n'importe quelle offre d'emploi et obtenez des retours personnalisés en temps réel sous forme de score et d'axes d'amélioration.",
        link: "https://launch-unlocked.lovable.app/",
        tags: ["IA / LLM", "RH", "Productivité", "Coaching"],
        image: "icon:Brain",
      },
    ]
  },
  en: {
    personalInfo: {
      name: "Space Informatik",
      ceo: "Djidepo Kokou Norbert NKRO",
      title: "Innovative Digital Solutions | Big Data & AI",
      bio: "Space Informatik is more than a development company; it is a strategic partner for innovation. Founded with the vision of propelling African and international companies into the future, we design complete digital ecosystems. From robust Cloud infrastructure to captivating user interfaces, including predictive analysis via AI, we turn complex challenges into sustainable growth opportunities.",
      email: "nkro006@gmail.com",
      phone: "00(228)70839500 / 00(228)70152456",
      location: "Avedji, 55788, Lomé, Togo",
      linkedin: "linkedin.com/in/norbert-nkro-143576187",
      github: "github.com/nkrokokou",
    },
    skills: [
      { name: "Agile & CI/CD Methodologies", category: "Innovation" },
      { name: "Python (Flask, Django)", category: "Backend" },
      { name: "Flutter & Dart", category: "Mobile" },
      { name: "PHP (Laravel)", category: "Backend" },
      { name: "HTML/CSS/JS", category: "Frontend" },
      { name: "C/C++", category: "Systems" },
      { name: "SQL & NoSQL", category: "Database" },
      { name: "Big Data & AI", category: "Data" },
      { name: "Virtualization", category: "DevOps" },
      { name: "Next.js & React", category: "Frontend" },
      { name: "FastAPI", category: "Backend" },
      { name: "Supabase", category: "Database" },
      { name: "Tailwind CSS", category: "Frontend" },
      { name: "Three.js / React Three Fiber", category: "Frontend" },
      { name: "Streamlit", category: "Frontend" },
      { name: "Turborepo", category: "DevOps" },
    ],
    experience: [
      {
        title: "Technology Partnership",
        company: "AMAP Togo",
        location: "Lomé, Togo",
        period: "Ongoing",
        description: [
          "Development of global solutions for sustainable agriculture and short supply chains.",
          "Implementation of a platform connecting local producers and consumers.",
          "Design of management tools for peasant farming associations.",
          "Technical support and guidance in the digital transformation of the agricultural sector.",
        ],
      },
      {
        title: "Technology Partnership",
        company: "Kekeli Efficient Power",
        location: "Lomé, Togo",
        period: "Ongoing",
        description: [
          "Development and maintenance of the company's information system.",
          "Design of digital solutions to optimize internal processes.",
          "Technical support and team training.",
        ],
      },
      {
        title: "Digital Transformation Projects",
        company: "Kheir Media",
        location: "Lomé, Togo",
        period: "11/2022 – 06/2023",
        description: [
          "Optimization and redesign of web applications to improve performance.",
          "Collaboration with multidisciplinary teams on innovative projects.",
          "Client needs analysis and custom solution design.",
          "Full-stack development of web and mobile applications.",
        ],
      },
    ],
    projects: [
      {
        title: "Phone Shop Manager",
        description: "Comprehensive management solution for phone shops: Point of Sale (POS), repair tracking (IMEI, issues), microfinance module (Tontine), and training center management. A robust application featuring PDF export, financial reports, and smart inventory management.",
        link: "https://phoneshop-manager.vercel.app/",
        github: "https://github.com/nkrokokou/phoneshop_manager",
        tags: ["SaaS", "ERP", "Sales", "Repairs", "Finance"],
        image: "icon:Smartphone",
      },
      {
        title: "Shalo Snap Photo",
        description: "Professional portfolio for a contemporary photographer, showcasing portraits, weddings, and special events. Elegant design and immersive gallery.",
        tags: ["Photography", "Portfolio", "Design"],
        image: "/images/shalo.png",
        isCompleted: true,
      },
      {
        title: "DressingFlow",
        description: "Fashion e-commerce platform offering a seamless shopping experience. Payment integration and catalog management.",
        github: "https://github.com/nkrokokou/dressingflow",
        tags: ["E-commerce", "Fashion", "Web"],
        image: "/images/dressingflow.png",
      },
      {
        title: "Cantine Kekeli",
        description: "'Les Délices de Victoire' meal management app for companies. Order optimization, employee area, and complete administration.",
        tags: ["Web App", "Management", "SaaS"],
        image: "/images/cantine.png",
        isCompleted: true,
      },
      {
        title: "Fermagroecologie",
        description: "Platform dedicated to agroecology, connecting farmers to sustainable practices and offering educational resources for eco-friendly agriculture.",
        tags: ["Ecology", "Agriculture", "Education"],
        image: "/images/fermagro.png",
        isCompleted: true,
      },
      {
        title: "FindMe",
        description: "Innovative geolocation application to find objects or people in real-time. Intuitive interface and secure tracking features.",
        tags: ["Geolocation", "App", "Utility"],
        image: "/images/findme.png",
        isCompleted: true,
      },
      {
        title: "Lomé Services",
        description: "Connecting local service providers and clients in Lomé. Various categories with direct contact via WhatsApp.",
        github: "https://github.com/nkrokokou/lome-services",
        tags: ["Marketplace", "Services", "WhatsApp"],
        image: "/images/lome-services.png",
      },
      {
        title: "Malodoc V2",
        description: "Modern health platform connecting patients and verified doctors. Online consultation booking, solidarity slots, and pharmacy management.",
        github: "https://github.com/nkrokokou/malodoc-v2",
        tags: ["Healthcare", "SaaS", "Web App"],
        image: "/images/malodoc.png",
      },
      {
        title: "Ziris",
        description: "Full-stack project combining FastAPI (Python) backend and React TypeScript frontend. Modern architecture with full documentation.",
        github: "https://github.com/nkrokokou/ziris",
        tags: ["Full-Stack", "FastAPI", "React", "Open Source"],
        image: "/images/ziris.png",
      },
      {
        title: "Compliance Management",
        description: "Regulatory and normative compliance management mobile application. ISO 14001:2015 monitoring, GDPR, and risk management.",
        tags: ["Mobile App", "Compliance", "ISO", "GDPR"],
        image: "/images/compliance-app.png",
        isCompleted: true,
      },
      {
        title: "CEFAPE Togo",
        description: "Modern website for the Centre de Formation Agricole and de Production Écologique. 3D interactive tomato plant model and comprehensive information about sustainable agriculture.",
        link: "https://cefape-togo.vercel.app/",
        github: "https://github.com/nkrokokou/cefape-togo",
        tags: ["Education", "Agriculture", "3D", "Web"],
        image: "/images/cefape.png",
      },
      {
        title: "AMAP Togo",
        description: "Complete e-commerce and management platform for the Association for the Maintenance of Peasant Agriculture in Togo. Monorepo featuring a bio products catalog, weekly basket subscription management, sales point (POS), and an admin back-office.",
        link: "https://www.fermagroecologie.org/",
        github: "https://github.com/nkrokokou/amap-togo",
        tags: ["Next.js", "Supabase", "Turborepo", "Monorepo", "E-commerce", "SaaS"],
        image: "icon:Leaf",
      },
      {
        title: "EduPerformance",
        description: "Academic performance evaluation platform. Interactive dashboard displaying key performance indicators (KPIs), dynamic charts (Chart.js), Pandas data processing, and a FastAPI backend.",
        link: "https://edu-performance.vercel.app",
        github: "https://github.com/nkrokokou/edu_performance",
        tags: ["FastAPI", "Pandas", "Python", "Chart.js", "Bootstrap"],
        image: "icon:GraduationCap",
      },
      {
        title: "Saadé Management",
        description: "Comprehensive management system for the Saadé restaurant/lounge. Interactive 3D interface (Three.js/Framer Motion) featuring stock management, inventory, kitchen waste tracking, HR, and accounting modules.",
        link: "https://proshop-ultra.vercel.app",
        github: "https://github.com/nkrokokou/proshop-ultra",
        tags: ["React", "Three.js", "Framer Motion", "Tailwind CSS", "Dashboard 3D"],
        image: "icon:Utensils",
      },
      {
        title: "Resume Matcher AI",
        description: "Intelligent resume screening and interview preparation assistant. Analyzes match percentage (NLP) between a CV (PDF/DOCX) and a job description, detects missing skills, and generates targeted questions (OpenRouter API).",
        tags: ["Python", "Streamlit", "LLM / AI", "NLP", "HR Tech"],
        image: "icon:Users",
        isCompleted: true,
      },
      {
        title: "Saadé Good Vibes",
        description: "Poetic pastry, handmade sweets, concept-store, and gourmet hot dogs in Lomé. A warm universe combining treats and sharing.",
        link: "https://saade-good-vibes.lovable.app/",
        tags: ["Pastry", "Concept-store", "Food & Beverage", "Lomé"],
        image: "icon:Store",
      },
      {
        title: "InterviewMate",
        description: "Practice for job interviews with an AI coach. Paste any job description, answer tailored questions, and get real-time scored feedback with actionable improvement tips.",
        link: "https://launch-unlocked.lovable.app/",
        tags: ["AI / LLM", "HR Tech", "Productivity", "Coaching"],
        image: "icon:Brain",
      },
    ]
  }
};
